const LIKES_DATA = "LIKES_DATA";
const HISTORY_DATA = "HISTORY_DATA";
const WATCH_LATER_DATA = "WATCH_LATER_DATA";
const PLAYLIST_DATA = " PLAYLIST_DATA";
const SINGLE_PLAYLIST = "SINGLE_PLAYLIST"

export { LIKES_DATA, HISTORY_DATA, WATCH_LATER_DATA,SINGLE_PLAYLIST,  PLAYLIST_DATA };
